// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package datasource

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name,phone,password, signed_for) VALUES ($1, $2, $3, $4) RETURNING id, name, phone, password, signed_for, created_at, update_at
`

type CreateUserParams struct {
	Name      string    `json:"name"`
	Phone     string    `json:"phone"`
	Password  string    `json:"password"`
	SignedFor SignedFor `json:"signed_for"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Phone,
		arg.Password,
		arg.SignedFor,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Password,
		&i.SignedFor,
		&i.CreatedAt,
		&i.UpdateAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, name, password, signed_for FROM users WHERE phone = $1 LIMIT 1
`

type GetUserByPhoneRow struct {
	ID        pgtype.UUID `json:"id"`
	Phone     string      `json:"phone"`
	Name      string      `json:"name"`
	Password  string      `json:"password"`
	SignedFor SignedFor   `json:"signed_for"`
}

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (GetUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i GetUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Password,
		&i.SignedFor,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users set name = $2 WHERE id = $1 RETURNING id, name, phone, password, signed_for, created_at, update_at
`

type UpdateUserParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Password,
		&i.SignedFor,
		&i.CreatedAt,
		&i.UpdateAt,
	)
	return i, err
}
